Document: deepin-sdk
Title: Debian deepin-sdk Manual
Author: <insert document author here>
Abstract: This manual describes what deepin-sdk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/deepin-sdk/deepin-sdk.sgml.gz

Format: postscript
Files: /usr/share/doc/deepin-sdk/deepin-sdk.ps.gz

Format: text
Files: /usr/share/doc/deepin-sdk/deepin-sdk.text.gz

Format: HTML
Index: /usr/share/doc/deepin-sdk/html/index.html
Files: /usr/share/doc/deepin-sdk/html/*.html
